sysD_unamed:
	gcc systemD/Unamed/semaphore.c -o s -lpthread

sysD_named:
	gcc systemD/Named/semaphore_w.c -o w 
	gcc systemD/Named/semaphore_r.c -o r

sysV:
	gcc systemV/semaphore_w.c -o w 
	gcc systemV/semaphore_r.c -o r