# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-vinh"
BBFILE_PATTERN_meta-vinh = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-vinh = "6"

LAYERDEPENDS_meta-vinh = "core"
LAYERSERIES_COMPAT_meta-vinh = "kirkstone"
