v4_s:
	gcc ipv4_stream/server.c -o s
	gcc ipv4_stream/client.c -o c

v4_d:
	gcc ipv4_dgram/server.c -o s
	gcc ipv4_dgram/client.c -o c

ux_s:
	gcc unix_stream/server.c -o s
	gcc unix_stream/client.c -o c

ux_d:
	gcc unix_dgram/server.c -o s
	gcc unix_dgram/client.c -o c
	
