sysV:
	gcc systemV/writer.c -o w
	gcc systemV/reader.c -o r

sysD_named:
	gcc systemD_POSIX/Named/writer.c -o w
	gcc systemD_POSIX/Named/reader.c -o r

sysD_anony:
	gcc systemD_POSIX/Anonymous/main.c -o m

file_m:
	gcc File_mapping/writer.c -o w
	gcc File_mapping/reader.c -o r
